ControllersAndActions/Controllers/DerivedController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControllersAndActions.Controllers
{
    public class DerivedController : Controller
    {
        public ViewResult Index() =>
            View("Result", $"This is a dervied controller");

        public ViewResult Headers() => View("DictionaryResult",
            Request.Headers.ToDictionary(kvp => kvp.Key,
                kvp => kvp.Value.First()));
    }
}

ControllersAndActions/Controllers/ExampleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControllersAndActions.Controllers
{
    public class ExampleController : Controller
    {
        //public ViewResult Index()
        //{
        //    ViewBag.Message = "Hello";
        //    ViewBag.Date = DateTime.Now;
        //    return View();
        //}

        //public JsonResult Index() => Json(new[] { "Alice", "Bob", "Joe" });
        //public ContentResult Index() => Content("[\"Alice\",\"Bob\",\"Joe\"]", "application/json");
        public ObjectResult Index() => Ok(new string[] { "Alice", "Bob", "Joe" });

        public VirtualFileResult bootstrap()
        => File("/lib/bootstrap/dist/css/bootstrap.css", "text/css");

        //public RedirectToActionResult Redirect() => RedirectToAction(nameof(HomeController), nameof(HomeController.Index));
        public RedirectToActionResult Redirect() => RedirectToAction(nameof(Index));

        // Mit dem Cast der Zeichenkette zum Objekt verhindert man das MVC
        // den String fehlinterpretiert und als Viewnamen deutet (und nach etwas suchen würde was nicht exesatiert)
        public ViewResult Result() => View((object)"Hello World");

        /*public RedirectResult Redirect() => Redirect("/Example/Index");*/

        //public RedirectToRouteResult Redirect() =>
        //    RedirectToRoute(new { controller = "Example",
        //        action = "Index",
        //        ID = "MyID" });
    }
}

ControllersAndActions/Controllers/HomeController.cs
using ControllersAndActions.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ControllersAndActions.Controllers
{
    public class HomeController : Controller
    {
        public ViewResult Index() => View("SimpleForm");

        //public ViewResult ReceiveForm()
        //{
        //    var name = Request.Form["name"];
        //    var city = Request.Form["city"];
        //    return View("Result", $"{name} lives in {city}");
        //}

        // Actionmethode die über gleichlautende Parameternamen vom Client Parameterwerte zugewiesen bekommt
        //public ViewResult ReceiveForm(string name, string city)
        //    => View("Result", $"{name} lives in {city}");

        // Pattern: Post/Redirect/Get
        [HttpPost]
        public RedirectToActionResult ReceiveForm(string name, string city)
        {
            TempData["name"] = name;
            TempData["city"] = city;
            return RedirectToAction(nameof(Data));
        }

        public ViewResult Data()
        {
            string name = (string)TempData["name"];
            string city = (string)TempData["city"];
            return View("Result", $"{name} lives in {city}");
        }
        // Generieren einer Antwort über ein Http Response context object
        //public void ReceiveForm(string name, string city)
        //{
        //    Response.StatusCode = 200;
        //    Response.ContentType = "text/html";
        //    byte[] content = Encoding.ASCII.GetBytes($"<html><body>{name} lives in {city}</body>");
        //    Response.Body.WriteAsync(content, 0, content.Length);
        //}

        //public IActionResult ReceiveForm(string name, string city)      
        //    => new CustomHtmlResult
        //       {
        //           Content = $"{name} lives in {city}"
        //       };

    }
}

ControllersAndActions/Controllers/PocoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ControllersAndActions.Controllers
{
    public class PocoController
    {
        // Context von MVC holen
        [ControllerContext]
        public ControllerContext ControllerContext { get; set; }

        // public string Index() => "This is a POCO controller";

        public ViewResult Index() => new ViewResult()
        {
            ViewName = "Result",
            ViewData = new ViewDataDictionary(
                new EmptyModelMetadataProvider(),
                new Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary())
            {
                Model = $"This is a POCO controller"
            }
        };

        public ViewResult Headers() =>
            new ViewResult()
            {
                ViewName = "DictionaryResult",
                ViewData = new ViewDataDictionary(
                    new EmptyModelMetadataProvider(),
                    new ModelStateDictionary())
                {
                    Model = ControllerContext.HttpContext.Request.Headers.ToDictionary(kvp => kvp.Key, kvp => kvp.Value.First())
                }
            };
    }
}

ControllersAndActions/Views/Example/Index.cshtml
@*@model DateTime*@
@{ Layout = null; }

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width-device-width" />
    <title>Controllers and Actions v1</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.css" />
</head>
<body class="m-1 p-1">
    <p>The day is: @ViewBag.Date.DayOfWeek</p>
    <p>The message is: @ViewBag.Message</p>
</body>
</html>

ControllersAndActions/Views/Shared/Bootstrap.cshtml
@{ Layout = null; }

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width-device-width" />
    <title>Controllers and Actions</title>
    <link rel="stylesheet" href="@Url.Action("Index","Example")" />
</head>
<body class="m-1 p-1">
    <form methode="post" asp-action="ReceiveForm">
        <div class="form-group">
            <label for="name">Name:</label>
            <input class="form-control" name="name" />
        </div>
        <div class="form-group">
            <label for="name">City:</label>
            <input class="form-control" name="city" />
        </div>
        <button class="btn btn-primary center-block" type="submit">Submit</button>
    </form>
</body>
</html>

ControllersAndActions/Views/Shared/IDictionaryResult.cshtml
@model IDictionary<string, string>
@{ Layout = null; }

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width-device-width" />
    <title>Controllers and Actions</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.css" />
</head>
<body class="m-1 p-1">
    <table class="table table-bordered table-sm table-striped">
        <tr><th>Name</th><th>Value</th></tr>
        @foreach (string key in Model.Keys)
        {
            <tr><td>@key</td><td>@Model[key]</td></tr>
        }
    </table>
</body>
</html>

ControllersAndActions/Views/Shared/Result.cshtml
@model string
@{ Layout = null; }

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width-device-width" />
    <title>Controllers and Actions</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.css" />
</head>
<body class="m-1 p-1">
    Model Data: @Model
</body>
</html>

ControllersAndActions/Views/Shared/SimpleForm.cshtml
@{ Layout = null; }

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width-device-width" />
    <title>Controllers and Actions</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.css" />
</head>
<body class="m-1 p-1">
    <form methode="post" asp-action="ReceiveForm">
        <div class="form-group">
            <label for="name">Name:</label>
            <input class="form-control" name="name" />
        </div>
        <div class="form-group">
            <label for="name">City:</label>
            <input class="form-control" name="city" />
        </div>
        <button class="btn btn-primary center-block" type="submit">Submit</button>
    </form>
</body>
</html>